### ISSUE TITLE
Burp plugin Ping error

### ISSUE THREAD

**Issue by samiux** [jaeles-project/jaeles#1]
**Command used :** 
(1) jaeles server --verbose
(2) The JWT Token has been saved in ~/.jaeles-burp/config.json.
(3) Login UI with the creds.

**Procedure to produce :** 
When pressing the "Test Connection" button in Burp Suite Community Edition, the jaeles server produced "401" error.  Meanwhile, the "Send to Endpoint" does not work too.

**Comment by j3ssie** [comment]
I've just push new features for easily integration with Burp.
Delete old config and update the latest version of Jaeles and Burp plugin.

```
rm -rf ~/.jaeles/
go get -u github.com/jaeles-project/jaeles
```

Watch this video https://youtu.be/1lxsYhfTq3M for more detail.
