### ISSUE TITLE
Scan  error 

### ISSUE THREAD

**Issue by 1522402210** [jaeles-project/jaeles#10]
![image](https://user-images.githubusercontent.com/25600994/74100543-34f0c680-4b6b-11ea-9131-106d0061b7dd.png)

![image](https://user-images.githubusercontent.com/25600994/74100553-4934c380-4b6b-11ea-8f70-b21c4ee4c06d.png)

![image](https://user-images.githubusercontent.com/25600994/74100512-fc50ed00-4b6a-11ea-939d-d7ff91e876ec.png)

error:

Jaeles Loaded ...
[+] Ready to send request to http://127.0.0.1:5000/api/parse
Import to external Jaeles ...
<urllib2.Request instance at 0x4>
[+] Send request to http://127.0.0.1:5000/api/parse
------------------------------
Import to external Jaeles ...
<urllib2.Request instance at 0x6>

why ?

thanks @j3ssie

**Comment by 1522402210** [comment]
i'm wating - - 3Q

**Comment by 1522402210** [comment]
Is it because there is no Signature rule?
Can you give some existing examples of Signature? Like XSS, Sqli, SSRF, open-redirect, etc., for everyone to learn, and then change it according to your needs?
Thank you
@j3ssie

**Comment by j3ssie** [comment]
You should take a look at [signature repo](https://github.com/jaeles-project/jaeles-signatures) and the [document site](https://jaeles-project.github.io/installation/) first.
