### ISSUE TITLE
No signature loaded

### ISSUE THREAD

**Issue by inthenets** [jaeles-project/jaeles#12]
Trying to execute the CLI:

```
$ jaeles scan -u https://localhost:8080

[Error] No signature loaded
```

Prior to execution, jaeles config -a init and -a update were ran to ensure signatures were available.

Is there something else to do?

Thanks!

**Comment by j3ssie** [comment]
It should be fixed in the latest update. Get latest Jaeles then run `jaeles config -a update`.
Default signatures will store in `~/.jaeles/base-signatures/`

**Comment by eyal-gabay** [comment]
me too same problem here

**Comment by eyal-gabay** [comment]
sorry i misunderstood the usage
we sould put "*" in the -s flag to scan all the stuff
