### ISSUE TITLE
Suspected bug when running basic scan

### ISSUE THREAD

**Issue by m82a3** [jaeles-project/jaeles#22]
After the basic signature is scanned, jaeles does not stop running or print the vulnerability results of the scan, but still sending just four packets of HEAD, POST, GET, PATCH, the requested url is the same, just like DDOS .
I have executed reload --signDir jaeles-signatures, the command used when scanning is
  ./jaeles-v0.9 scan -u https://seaii-blog.com -v.
My operating system is osx.
![image](https://user-images.githubusercontent.com/21202283/84753351-77cb1b00-aff1-11ea-9bad-31fb6a6dfb1d.png)

**Comment by j3ssie** [comment]
You literally just select **ALL** signatures. So it works as expected.

Please read documentation or at least this [Usage](https://github.com/jaeles-project/jaeles#usage) in README.

**Comment by m82a3** [comment]
You can just test testphp.vulnweb.com with the same parameters as me, the result is definitely the same. This script will only issue the same request after testing all signatures, until the testphp.vulnweb.com scan is paralyzed.
