### ISSUE TITLE
# github.com/mattn/go-sqlite3 sqlite3-binding.c: In function ‘sqlite3SelectNew’: sqlite3-binding.c:129019:10: warning: function may return address of local variable [-Wreturn-local-addr] 129019 |   return pNew;        |          ^~~~ sqlite3-binding.c:128979:10: note: declared here 128979 |   Select standin;        |          ^~~~~~~

### ISSUE THREAD

**Issue by gauravdrago** [jaeles-project/jaeles#27]
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:129019:10: warning: function may return address of local variable [-Wreturn-local-addr]
129019 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128979:10: note: declared here
128979 |   Select standin;
       |          ^~~~~~~

**Comment by j3ssie** [comment]
Please provide more info like what command you ran or what is your OS?
