### ISSUE TITLE
How to add a new signature manually?

### ISSUE THREAD

**Issue by thisEdgarMarquez** [jaeles-project/jaeles#3]
Hello, I would like to know how to add a new signature manually since through the UI a 404 error returns, please and thank you

**Comment by j3ssie** [comment]
Just follow this [docs](https://jaeles-project.github.io/signatures/) to understand a signature and this [repo](https://github.com/jaeles-project/jaeles-signatures) for more examples.

If your question is how to load new Signature to a DB? Just save it to anywhere then load it by the command below.
```
jaeles config -a reload -F /tmp/custom-signatures/
```
with `/tmp/custom-signatures/` is your custom signature folder.

Or you can just use new signature directly by using this command
`jaeles scan -s new_sign.yaml -u example.com`

Let me know if you have any question?

**Comment by thisEdgarMarquez** [comment]
Thanks it worked for me, look in the documentation but I didn't find information on how to add them to the database. Thanks again
